### ISSUE TITLE
Hosting to heroku not working. Help needed

### ISSUE THREAD

**Issue by osazemeu** [contentful/contentful_middleman_examples#3]
Nothing seems to be working. I created a config.ru file for heroku and even filled in environment variables. It doesn't seems to bulge. Logs ain't even showing anything meaningful.

```
require 'middleman/rack'
run Middleman.server
```

![capture](https://cloud.githubusercontent.com/assets/7466259/16353380/4eb103e6-3a71-11e6-9ec0-e70e77c8b90d.PNG)

**Comment by dlitvakb** [comment]
Hey @osazemeu,

Middlemana is not intended to be ran as a server, it's a static site generator, therefore no need for a running server. Using GitHub Pages or Amazon S3 + some caching would be far more efficient.

Still if you want to proceed with the Heroku route, following this tutorial might be helpful https://jordanelver.co.uk/blog/2014/02/17/how-i-deployed-middleman-to-heroku/

Hope that helps

Cheers

**Comment by osazemeu** [comment]
thanks for the heads up
