### ISSUE TITLE
Contentful key in config.rb

### ISSUE THREAD

**Issue by mikesimmonds** [contentful/contentful_middleman_examples#4]
HI there,
I notice you have your contentful access token and space id in the config.rb file - Is this safe? 

Thanks for the great examples,
Mike

**Comment by dlitvakb** [comment]
Hey @MichaelSimmonds,

Delivery API tokens are read-only keys, therefore safe to share if content is not sensitive/private.

You should store them on the environment or use other techniques if your content is not meant to be publicly available through means other than your applications.

Hope that helps,

Cheers

**Comment by mikesimmonds** [comment]
I understand. Thanks for clarifying - I hadn't realised they are read-only.

Many thanks,

Mike

**Comment by dlitvakb** [comment]
No problem!

Glad to help,

Cheers
